### PR TITLE
Add support for reading and writing OME-TIFF with sub-resolutions

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Support reading OME-TIFF pyramids, as already implemented in Bio-Formats.

- Add two-level (series, resolution) `CoreMetadataList`
- Drop flat `CoreMetadataList` and associated `coreIndex` (unlike Bio-Formats, this doesn't have the same compatibility concerns, and it greatly simplifies the implementation)
- Split up the `initFile` method in `OMETIFFReader` into several helper functions; this makes it easier to reason about the scope and ordering of actions during setup, as well as allowing reuse of some of the helpers needed by the the sub-resolution setup
- Read and use the IFDs references by `SUBIFDS` to create the extra `CoreMetadata` resolution list elements
- `openBytes` will chose the IFD for the current series and resolution
- Update all unit tests to match the changed behaviour

Support writing OME-TIFF pyramids, similar to how it is implemented in https://github.com/openmicroscopy/bioformats/pull/3189

- Add helper functions to `MetadataTools` to add, query and remove resolution annotations on the metadata store
- Add sub-resolution methods to `FormatWriter`, and additionally expose some core metadata methods already implemented in `detail/FormatWriter`, so that e.g. SizeX and SizeY can be correctly introspected for the current resolution
- FormatWriter strips off the resolution annotations before writing is completed, so they don't get serialised
- TIFF wrapper changes include adding the sub-file type bit flags, adding subifd convenience methods to IFD, and adding support for writing IFDs to the TIFF interface, and flushing tiles in any order (needed for multi-threaded tile writing)
- OME-TIFF changes include adding IFD to the per-plane state (used by the reader), handling IFD and Sub-IFD flushing and switching when writing
- Unit test ensures that round-tripping of basic metadata and pixel data works.
- Example demonstrates rather more sophisticated use of pyramids, generating fractals at arbitrary scale, using multi-sampling for image quality and multi-threaded tile generation and writing to make it scale up to as many cores as you have free.

Other changes for safety, usability and performance:

- Classes hiding their internal state via `Impl` classes now use `unique_ptr` instead of `shared_ptr`.  This is both more efficient and safer since sharing of the impl object between instances is impossible.
- PixelBuffer size reduced from 9D to 4D; this has significant performance impact, speeding up every index calculation by 2.25×; iterating over pixel buffers is a significant bottleneck and this is a huge improvement.  It's also much easier and safer to use now, with there being two variants (interleaved, non-interleaved, rather than 12, where previously the six dimension orders were also taken into consideration).
- Unused helper functions dropped from OMETIFFWriter; removes some compiler warnings
- TileBuffer: Use `vector` rather than custom allocation of memory; it's safer and no less efficient

Sample files (uploaded to glencoe FTP server) for use as reference files and for testing:

- fractals-small.ome.tiff (baseline TIFF)
- fractals.ome.tiff (BigTIFF)

Testing:

- Run `ome-files info` on a pyramid OME-TIFF and check the resolution level count and dimensions match the expected number and sizes
- Run `ome-files view` with a pyramid OME-TIFF as documented in https://github.com/ome/ome-qtwidgets/pull/42 and check that the levels can be displayed correctly
- Run `./examples/subresolution fractal-example.ome.tiff` and check this with `tiffinfo [-o offset]`, `tiffgt [-o offset]`, `showinf -noflat -series n -resolution m` and `ome-files info` to check that the top-level IFDs and SubIFDs are present and correct and reported and viewed correctly by all the tools.  You might run into memory limits with `showinf` for the largest resolutions.
- Review the documentation addition on the tutorial page.

See also:

- https://github.com/ome/ome-qtwidgets/pull/42
- https://github.com/ome/ome-files-py/pull/30
- https://github.com/openmicroscopy/ome-files-performance/pull/62

/cc @dsudar

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Example `ome-files info` output:

```
% ome-files info ~/scratch/pyramid/inbox/curated/ome-tiff/sub-resolution/Leica-1/Leica-1-subifds.ome.tiff 
Image: /home/rleigh/scratch/pyramid/inbox/curated/ome-tiff/sub-resolution/Leica-1/Leica-1-subifds.ome.tiff
Using reader: OME-TIFF (Open Microscopy Environment TIFF)
Reader setup took 00:00:00.145211

Filename = "/home/rleigh/scratch/pyramid/inbox/curated/ome-tiff/sub-resolution/Leica-1/Leica-1-subifds.ome.tiff"
Used files = ["/home/rleigh/scratch/pyramid/inbox/curated/ome-tiff/sub-resolution/Leica-1/Leica-1-subifds.ome.tiff"]

Reading core metadata
Series count = 2

Series #0:
        Resolutions = 3
                #0 = 1616 × 4668
                #1 = 404 × 1167
                #2 = 101 × 291
        Image count = 1
        RGB = [true] ([3]) 
        Interleaved = true
        Indexed = false
        Width = 1616
        Height = 4668
        SizeZ = 1 (effectively 1)
        SizeT = 1 (effectively 1)
        SizeC = 3 (effectively 1)
        Thumbnail size = 44 × 128
        Endianness = little
        DimensionOrder = XYCZT (certain)
        PixelType = uint8
        Bits per Pixel = 8
        MetadataComplete = true
        ThumbnailSeries = false

Series #1:
        Resolutions = 5
                #0 = 36832 × 38432
                #1 = 9208 × 9608
                #2 = 2302 × 2402
                #3 = 576 × 600
                #4 = 144 × 150
        Image count = 1
        RGB = [true] ([3]) 
        Interleaved = true
        Indexed = false
        Width = 36832
        Height = 38432
        SizeZ = 1 (effectively 1)
        SizeT = 1 (effectively 1)
        SizeC = 3 (effectively 1)
        Thumbnail size = 122 × 128
        Endianness = little
        DimensionOrder = XYCZT (certain)
        PixelType = uint8
        Bits per Pixel = 8
        MetadataComplete = true
        ThumbnailSeries = false

Global metadata:
        BitsPerSample: 8
        Compression: JPEG
        ImageLength: 4668
        ImageWidth: 1616
        MetaDataPhotometricInterpretation: RGB
        NumberOfChannels: 3
        PhotometricInterpretation: YCbCr
        PlanarConfiguration: Chunky
        ReferenceBlackWhite: 0
        ResolutionUnit: Centimeter
        SamplesPerPixel: 3
        TileLength: 512
        TileWidth: 512
        XResolution: 608.3301634770519
        YCbCrSubSampling: chroma image dimensions are half the luma image dimensions
        YResolution: 608.3301634770519
        image_0000001819 (R0) collection.name: ImageCollection_0000000128
        image_0000001819 (R0) collection.uuid: urn:uuid:d0fa25ee-baa8-48cd-944d-5598a36b3f7b
        image_0000001819 (R0) creationDate: 2011-05-31T09:43:06.873Z
        image_0000001819 (R0) device.model for image: Leica SCN400;Leica SCN
        image_0000001819 (R0) device.version for image: 1.4.0.9691 2011/03/30 10:30:59;1.4.0.9708
        image_0000001819 (R0) scanSettings.illuminationSettings.illuminationSource for image: brightfield
        image_0000001819 (R0) scanSettings.illuminationSettings.numericalAperture for image: 0.4
        image_0000001819 (R0) scanSettings.objectiveSettings.objective for image: 20
        image_0000001819 (R0) view.offsetX for image: 5389341
        image_0000001819 (R0) view.offsetY for image: 17548313
        image_0000001819 (R0) view.sizeX for image: 18416000
        image_0000001819 (R0) view.sizeY for image: 19216000
        image_0000001819 (R0) view.spacingZ for image: 400
```

**Comment by sbesson** [comment]
As discussed in https://github.com/openmicroscopy/bioformats/pull/3189#issuecomment-409918842, our priority will be on the functional review of the Java work on OME-TIFF pyramids for the upcoming weeks but very promising to see this first version of the matching C++ work.

As a side note, several the OME Files daily builds have been failing for the last couple of days - see https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-trigger/ and downstream but we have not identified yet whether this was related to one of the recently opened PRs.

**Comment by rleigh-codelibre** [comment]
The build failures are due to:

- on Windows, the cmake PR for the ome-cmake-superbuild.  I'm re-testing that now; it might be a problem with the build node configuration, because it did build cleanly for me locally.
- on MacOS, this PR outputs a vector to a stream; works on all the other platforms but not on MacOS; I'll push a commit later this evening to output the nested elements one by one.

**Comment by rleigh-codelibre** [comment]
@sbesson I have pushed fixes for both the Windows and MacOS failures, and if you were to restart the jobs, they should now go green.

**Comment by rleigh-codelibre** [comment]
This PR has now been extended with sub-resolution writing support as well.  This includes the ability to add, retrieve and remove sub-resolution annotations to the metadata store, updates to the writer API to enable sub-resolutions and to introspect the dimensionality and tile size changes across resolutions), and the necessary changes to the TIFF and OME-TIFF writing code to emit sub-resolution TIFFs using SubIFDs.  Additionally, unit tests and examples are included, along with additions to the Sphinx documentation to demonstrate how to use the sub-resolution API.  The example program generates pyramids with these fractals in:

test-0

test-1

Additionally, while implementing these examples, I identified a large performance bottleneck in the pixel buffer, and saw big improvements by reducing its dimensionality.  These are also included here.

/cc @dsudar

**Comment by rleigh-codelibre** [comment]
See also: https://github.com/ome/ome-files-py/pull/30

**Comment by rleigh-codelibre** [comment]
Sample files `fractals-small.ome.tiff` and `fractals.ome.tiff` uploaded to glencoe FTP server.

**Comment by rleigh-codelibre** [comment]
Copied to [GitLab](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/103).

**Comment by rleigh-codelibre** [comment]
This pull request was split into separate pieces for review and testing:

- [!106](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/106) PixelBuffer: Decrease size from 9D to 4D
- [!107](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/107) Preparation for pyramid reading
- [!108](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/108) Test cleanup
- [!109](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/109) Add support for reading OME-TIFF with sub-resolutions
- [!110](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/110) Preparation for pyramid writing
- [!111](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/111) TIFF SubIFD support and cleanup
- [!103](https://gitlab.com/codelibre/ome-files-cpp/merge_requests/103) Add support for writing OME-TIFF with sub-resolutions

The full list of PRs merged in GitLab for a 0.6.0 release is [here](https://gitlab.com/codelibre/ome-files-cpp/merge_requests?scope=all&utf8=%E2%9C%93&state=merged)

If desired, this pull request may be closed.

**Comment by sbesson** [comment]
Closing as per announcement on the [OME mailing list](http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2018-August/004294.html). For those interested, please refer to this [set of repositories](http://lists.openmicroscopy.org.uk/pipermail/ome-devel/2018-November/004308.html).

**Pull request closed without merging**
