### PR TITLE
docs: Correct and check internal links

### PR DESCRIPTION
**Pull request by rleigh-dundee**
- Adjust all doxygen links to use relative paths in the install tree
- Add a validator tool which checks the validity of all such lock links, including anchors
- Add a `sphinx-linkcheck` cmake configuration option, plus targets to validate links
- Clean up any remaining sphinx warnings

While relative links are for the locally installed version of the documentation, this will work equally well for the documentation on the download page and the main website.

--------

Testing:

- Download https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge/BUILD_TYPE=Release,node=marlin/lastSuccessfulBuild/artifact/artefacts/binaries/
- unpack it
- open share/doc/ome-files/manual/html/schema.html and check that the `model` and `metadata` links work (they fail with the previous build)
- open share/doc/ome-files/manual/html/tutorial.html and check the various links work (they previously failed)

These links should redirect to the ome-common and ome-xml and ome-files API references.  These will be `share/doc/ome-$component/api/html/$link`

The link checking will be enabled in the superbuild with an additional PR.

### CODE REVIEW

**Comment by mtbc** [comment]
For unpacking the artifact I got a bunch of,
```
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
```
I don't think this is a problem blocking this PR, but http://lee.greens.io/blog/2014/05/06/fix-tar-errors-on-os-x/ suggests maybe we can easily not generate such weird archives? Could be something for the future anyway.

**Comment by mtbc** [comment]
`/share/doc/ome-xml/api/html/index.html` isn't the most inspiring page but, again, not this PR's fault.

**Comment by mtbc** [comment]
Are the changes to the link checking checked somehow so we do know that CI will still find bad links?

**Comment by rleigh-codelibre** [comment]
I'm working on the checking right now.  It's a separate PR to the superbuild to enable it.

You can test it by hand it you like, but it should be in the CI builds early next week.

**Comment by mtbc** [comment]
I'm not finding any broken docs links. I'd say go ahead and **merge this PR** and we'll look for link checking issues being revealed through @rleigh-dundee's coming work.

**Comment by hflynn** [comment]
Looks good to me too.

**Comment by rleigh-dundee** [comment]
https://github.com/ome/ome-cmake-superbuild/pull/75 is the followup.  Needs testing and maybe some additional tweaking before Monday.

**Comment by rleigh-codelibre** [comment]
I found a problem with regard to link checking in the context of the super-build, so this probably shouldn't be merged just yet.

**Comment by mtbc** [comment]
Aha. Should repeat the testing instructions for this, or will this commit effectively be tested by your other PR?

**Comment by rleigh-codelibre** [comment]
It will be tested by the other PR shortly.

**Comment by dgault** [comment]
Ive gone through all the files in the manual from the binary download.
There were no broken links in any of the files and all links directed to the correct file.

**Pull request merged**
