### PR TITLE
tiff: Remove support for libtiff < 4.0.3

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
None of the earlier versions have been tested by the CI or manually for over a year, and are unlikely to be used again.  Drop the untested codepaths.  This will mean there is only one supportedset of codepaths, and BigTIFF support is guaranteed.  For all the line removals, the codepaths for the `TIFF_HAVE_FIELD` and `TIFF_HAVE_BIGTIFF` conditions are kept, and all other paths are dropped.

Note that this does not have any impact upon the superbuild which was using current libtiff--the codepaths are unaffected.  Likewise for the supported platform builds.  The only affected users (if any) are those using old platforms who are not using the superbuild.  This combination is not supported, and has not been for a long time; the removed logic predates the superbuild and was added solely for travis which was stuck on ubuntu 12.04.  Essentially, the impact is minimal and this removal should be quite safe.

More detail:

- We remove the testing of version-specific features in `ImageLibraries.cmake`.  These features are now all guaranteed to be present, so checking for >= 4.0.3 is completely sufficient to ensure everything we need is present.
- We remove all the #defines from `tiff/config.h` and make it static rather than generated.  It's no longer needed, but I've left it present but empty in case anyone was #including it (unlikely--it was for internal use)
- Use of `tiff/config.h` is removed entirely from our code.
- We remove all `#if`/`#endif` statements for `TIFF_HAVE_FIELD` since this functionality is guaranteed to be present.  Likewise for `TIFF_HAVE_BIGTIFF`.
- We also remove all content in `#else` blocks for these conditions, since fallback codepaths are no longer used, and will never again be used.

### CODE REVIEW

**Comment by mtbc** [comment]
The diff looks good to me. :+1:

**Comment by rleigh-codelibre** [comment]
I've made a tiny additional change to make the deprecation warning visible at compile time rather than just being a comment.  No function change there.

**Comment by mtbc** [comment]
The diff looks plausible at least. :smiley: Nice to elevate from a comment into a message.

**Comment by sbesson** [comment]
Generally sounds reasonable, builds have been passing consistently and the change is in agreement with our decision for the platform requirements of OME Files C++ 0.2.x of setting 14.04 as the minimal Ubuntu supported version. The only other supported platform coming to my mind is CentOS 6.7 where the shipped libtiff version is still 3.9.4 if I remember correctly. Does this means the C++ library could only be built using the superbuild with this change?

**Comment by rleigh-codelibre** [comment]
@sbesson This is correct.  However, because CentOS does not provide other prerequisites such as Boost, the reality on this platform is that you must build with the superbuild or spend time building all the prerequisites yourself.  As a result, I don't think this has a significant impact on this platform--due to its age, the superbuild is a requirement for providing reasonably current and missing libraries for the platform.

**Comment by joshmoore** [comment]
Looking at https://github.com/joshmoore/cppspace/blob/master/centos6/Dockerfile I agree that this doesn't change the state of play for CentOS 6, and we could in turn encourage use of the superbuild for that platform. Moving forward, I'd be for making sure this info is encoded on our versions page during the platform support discussions over the next few months. i.e. split between platforms where we expect the package manager to provide everything needed and those for which the superbuild is necessary. (For me this is already quite similar to what we do with CentOS 6 & Python on the OMERO-side) :thumbsup:

**Comment by rleigh-codelibre** [comment]
@joshmoore Definitely agreed on the documentation front.  We can add a documentation page to the superbuild documentation which contains the information about the state of support for each platform.

**Comment by sbesson** [comment]
Thanks both. The last point (documentation update) had been briefly discussed with @rleigh-codelibre and is now captured as https://trello.com/c/8DYv96yZ/17-document-state-of-support-for-each-platform. Merging.

**Pull request merged**
