### PR TITLE
Fix copyright year range for main ome-files --version

### PR DESCRIPTION
**Pull request by sbesson**
See https://trello.com/c/4mdYwpIP/6-update-end-copyright-year

To test this PR check

```
ome-files --version
ome-files info --version
```

In both cases, the copyright should include 2017 in the year range

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
The code change is good to merge.  However, note that it also needs updating in `cmake/TemplateCmdWrapper.cmake.in` and `cmake/TemplateShellWrapper.cmake.in` for the ome-files wrapper scripts.

**Comment by sbesson** [comment]
Thanks will push an additional commit

**Comment by mtbc** [comment]
Ah, I guess that's why `ome-files-standalone-bundle-0.3.0-Release-Ubuntu14.04-x86_64-b536` still gives me `© 2006–2016`.

**Comment by rleigh-codelibre** [comment]
This is good to merge, thanks.

**Pull request merged**
