### PR TITLE
OMETIFFReader: Set interleaving according to IFD PlanarConfiguration

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Set the interleaved property correctly for the OME-TIFF reader (the other readers use the coremetadata conversion from till/Util.cpp which already has this behaviour).

Testing: Check builds are green.  There's no change to openbytes since the pixel buffer was already in the correct order; this simply corrects the isInterleaved property to match reality rather than fixing it to false.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
I've pushed a second commit here, to make round-tripping work; previously it would force interleaving off for single-sample images while it can now be set when requested.

**Comment by dgault** [comment]
Builds are green and the changes look fine and inline with whats in `Util.cpp`
I tested a read as well as a round trip write and read, everything behaved as expected.

PR looks good to merge

**Comment by sbesson** [comment]
Changes look definitely sensible. Functionally, this PR removes the unnecessary array copy in https://github.com/openmicroscopy/ome-files-performance/pull/11 and addresses the pixel writing benchmarking issues. :+1:

Note the ome-files-py [interleaved tests]((https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge/) are now failing (although the build is not failed which is another bug). Although it is not really the Python bindings' responsibility to test the underlying interleaved logic, I assume this matches the expected behavior for the OME-TIFF sample under https://github.com/ome/ome-files-py/tree/master/test/data. /cc @simleo 

More generally see https://trello.com/c/jYrO98MG/83-ome-tiff-interleaved-rgb for a discussion on limitations of the handling of interleaved data in Java/C++. Is there a general agreement on the behavioral changes proposed in this PR and should we modify the Java (OME-)TIFFReader readers acoordingly? For the Java `TiffWriter`, the condition reads as 

``` 
ifd.putIFDValue(IFD.PLANAR_CONFIGURATION,
      interleaved || getSamplesPerPixel() == 1 ? 1 : 2);
```

Is it correct to say that the additional `getSamplesPerPixel()` condition is not relevant in this case as per the TIFF specification and that these changes match the behavior of the TIFF writer or would there be corresponding Java changes here as well?
/cc @dgault @melissalinkert

**Comment by rleigh-codelibre** [comment]
There are a couple of parts of this to consider.  Firstly the low-level TIFF implementation.  In both cases, the C++ and Java behaviour is correct, but slightly different.  The Java behaviour here is to override the interleaved property if SPP=1.  In C++ we don't override the user's intent since it would break round-tripping, so you can request a non-standard (but valid) configuration.

At the reader level, the Java OMETiffReader forcibly defaults the interleaved property to false.  The reader can still be overridden, but that would then require a reordering of the data returned by openBytes for it to be correctly passed to saveBytes.  On the C++ side we require the data for openBytes and saveBytes to have a compatible structure, and this requires the interleaving for the reader and writer to match up.  Since the Java pixel data is an unstructured byte array, the C++ code is essentially being much more strict regarding the organisation of the data.

I'd like to relax the C++ buffer checks so that the interleaved property is essentially ignored when SPP==1.  This requires would require some work on the pixel buffer logic, such as replacing it with the code I presented last year.  This would allow the two implementations to then be more closely aligned in their behaviour.

**Comment by simleo** [comment]
Intuitively, the Java approach of setting the interleaved flag to false when there is only one sample per pixel looks "right" to me, since there is nothing to interleave. In practice, however, the property only makes sense when there are multiple samples per pixel, so `ome-files-py` is probably wrong in even checking it on a non-RGB file (unless we end up choosing a convention and documenting it).

**Comment by rleigh-codelibre** [comment]
From http://www.awaresystems.be/imaging/tiff/tifftags/planarconfiguration.html: "If SamplesPerPixel is 1, PlanarConfiguration is irrelevant, and need not be included.".  So we could drop it entirely when SPP==1.  However, the main purpose of this PR, irrespective of any future behaviour changes, is to ensure the read and write behaviour match each other for consistency.  The Java read and write behaviour do not, and we might have to live with that consistency until we can properly reconcile them.

**Comment by melissalinkert** [comment]
The commit that introduced the check on ```getSamplesPerPixel()``` on the Java side was https://github.com/openmicroscopy/bioformats/commit/f6dd2560c6c53243277281da0ce973f285d304d0
If that really does help make it possible to use exported TIFFs in other software, then reverting is probably not ideal.  At the very least, reverting that commit would require clear documentation for users explaining how they might be impacted.

On the reader side, changing TIFF-based readers to set ```interleaved``` according to ```PLANAR_CONFIGURATION``` is not a small change.  It would require substantial work in ```TiffSaver```, a one-line change to every TIFF-based reader, and associated configuration updates and testing for any existing TIFF or TIFF-based dataset with ```PLANAR_CONFIGURATION=2```.  It's certainly technically possible, and I'm not generally opposed to it in the long term, but given the effort required I don't know that it should be a high priority.

**Comment by sbesson** [comment]
Discussed with @rleigh-codelibre @dgault and @melissalinkert, given the existing implementation difference between Java and C++, the general consensus is that these do not bring us much further apart. Additionally, the long-term proposal in https://github.com/ome/ome-files-cpp/pull/49#issuecomment-277684970 should homogeneize the behavior.

Merging so that we can pursue the 0.3.0 work. The only immediate follow-up item that might be worth would be to document this difference in behavior e.g. via a short paragraph in the `conversion.txt` file explaining the difference between the languages?

**Comment by simleo** [comment]
I have changed (ome/ome-files-py#8) the expected result in the ome-files-py test to match the new C++ behaviour. Since the Python version is a wrapper around the C++ code, it should simply be consistent with it whatever the Java implementation does.

**Comment by rleigh-codelibre** [comment]
@sbesson I created https://trello.com/c/s6HdQNWu/82-document-differences-between-c-and-java-pixel-data-handling for the documentation side.

**Pull request merged**
