### PR TITLE
OME-TIFF fixes

### PR DESCRIPTION
**Pull request by rleigh-codelibre**
Collected OME-TIFF reader and writer fixes, ported from Java:

https://trello.com/c/1eK8vdcX/6-sync-ome-tiff-implementation-with-java
https://trello.com/c/4xUsxBUY/7-ome-tiff-tiffdata-handling

Testing: OME-TIFF files which would open with `ome-files info` should contine to work.  I'll be following this up with additional fixes needed to get all OME-TIFF samples to open correctly.

### CODE REVIEW

**Comment by rleigh-codelibre** [comment]
Note: Windows build failure fixed in the above commit and tested in https://ci.openmicroscopy.org/view/Files/job/OME-FILES-CPP-DEV-merge-win-superbuild/397/

**Comment by dgault** [comment]
The code here reads fine to me and covers the fixes as described. Tests and builds also look fine and testing various ome-tiff samples with ome-files works as expected.

Is there any other particular scenarios that should be tested for this PR?

**Comment by rleigh-codelibre** [comment]
Not that I can think of.  We'll add more comprehensive support as a followup.

**Comment by dgault** [comment]
Thanks, in that case this PR should be ready to merge.

**Comment by sbesson** [comment]
Correlating this with https://trello.com/c/uUX97Zzw/2-integration-tests-for-ome-tiff, is there a script containing the set of OME-TIFF samples that are currently supported as part of this PR? Or is it part of an upcoming PR?

**Comment by rleigh-codelibre** [comment]
There's no script at present; that's one of the tasks which still needs doing.

**Comment by sbesson** [comment]
Understood. Merging this as per https://github.com/ome/ome-files-cpp/pull/28#issuecomment-245245986.

**Comment by sbesson** [comment]
Note while  testing this against one of the [multi-file samples](http://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/tubhiswt-2D/) with this PR, I got the following exception:
```
ome-files (OME Files) 0.2.0-24-g059eadd (2016-09-08 05:06:35 +0100)
Copyright © 2006–2016 Open Microscopy Environment

This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
hudson@ubuntu-14042:~$ ./ome-files-standalone-bundle-0.2.0-24-g059eadd-Release-Ubuntu14.04-x86_64-b360/bin/ome-files info tubhiswt-2D/tubhiswt_C0.ome.tif 
Image: tubhiswt-2D/tubhiswt_C0.ome.tif
Using reader: OME-TIFF (Open Microscopy Environment TIFF)
E: Unmatched filename for UUID ‘urn:uuid:85a5ab3e-0ead-498f-b2cb-3531ea0788ef’
```

Is that expected? While the support for the modulo samples might take more time and is outside the scope of 0.2.2, I would expect support for multi-file OME-TIFF filesets should be complete with this PR.

**Comment by rleigh-codelibre** [comment]
I'm not sure.  I'd need to check if it's a regression introduced by this PR or if it's a defect which was already present.  There may well be corner cases remaining in the support which we haven't picked up on yet, but it *should* in theory be fully functional.

**Comment by sbesson** [comment]
@rleigh-codelibre: quickly tested various filesets, I can confirm there is at least a regression with the companion fileset which opened with 0.2.0 when selecting the `.ome.tiff`. For the other files, there is no regression but the goal is definitely to support our own OME-TIFF sample files for this release, this counts as a 0.2.1 blocker that we should fix either in the code or in the files themselves depending on the case. I opened https://trello.com/c/lw0AFxf6/27-fix-sample-2016-06-ome-tiff-files correspondingly.

**Pull request merged**
